# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BOq_E1bg-Cv_12Mjsj03ow51cssNn_V7
"""

import joblib
import pandas as pd

# Memuat model terbaik
best_model = joblib.load('/content/best_logistic_model.pkl')

# Memuat TfidfVectorizer yang sama (harus disimpan sebelumnya)
tfidf = joblib.load('/content/tfidf.pkl')  # Pastikan Anda menyimpan TfidfVectorizer sebelumnya

# Contoh data input yang ingin diprediksi
data_input = [
    "Saya sangat senang dengan produk ini!"
]

# Ekstraksi fitur dari data input
X_input_tfidf = tfidf.transform(data_input)  # Gunakan transform, bukan fit_transform

# Melakukan prediksi
predictions = best_model.predict(X_input_tfidf.toarray())

# Memperoleh probabilitas prediksi untuk setiap kelas
prediksi_probabilitas = best_model.predict_proba(X_input_tfidf.toarray())
print("Probabilitas Sentimen:", prediksi_probabilitas)

# Menentukan sentimen berdasarkan probabilitas dan threshold
threshold_netral = 0.5  # Threshold untuk menentukan sentimen netral
label = ["NEGATIF", "NETRAL", "POSITIF"]

# Logika untuk menentukan sentimen
if prediksi_probabilitas[0][1] > threshold_netral:
    print("Sentimen kalimat baru adalah NETRAL.")
elif prediksi_probabilitas[0][2] > prediksi_probabilitas[0][0]:  # Jika positif > negatif
    print("Sentimen kalimat baru adalah POSITIF.")
else:
    print("Sentimen kalimat baru adalah NEGATIF.")